### ISSUE TITLE
Some completions suggest dom0 but should not

### ISSUE THREAD

**Issue by neoniobium** [jamke/qubes-completion#15]
Some command like `qvm-shutdown` or `qvm-kill` suggest `dom0` as an target VM. This should not be the case.

Possible Solution:
- Remove `dom0` each time by hand.
- Rework `__get_qubes_list` and add new input arguments options  like `running-` for getting all running qubes but `dom0`

**Comment by jamke** [comment]
@neoniobium I would appreciate additional help for this suggestion - the list of commands that should not provide `dom0` as a target qube (including places in arg line).

**Comment by neoniobium** [comment]
I can will that. I will provide this later this week.

**Comment by neoniobium** [comment]
For a start:
- qvm-kill
- qvm-shutdown
- qvm-firewall
- qvm-pause
- qvm-run
- qvm-get-image
- qvm-get-tinted-image
- qvm-sync-appmenus
- qvm-clone
- qvm-move-to-vm
- qvm-copy-to-vm
- qubes-vm-clone
- qubes-vm-from-device
- qubes-vm-settings

**Comment by jamke** [comment]
OK, I used your list, thanks a lot. 
* I am not sure if it is full, but good improvement anyway.
* About `--exclude`: I decided to keep `dom0` in those because if user wants to explicitly exclude `dom0` to be sure, they should be allowed.
* About `qubes-guid` and `qubes-guivm-session` I am also not sure, the tools lack proper documentation, so I decided to keep them as this for now.

You may take a look. Related commits:
* 565a14d
* 711cc3a
* c3fb6b5

**Comment by neoniobium** [comment]
Looks good! If I notice something missing I will make PR for that.
