### ISSUE TITLE
Improve completion for `qubesctl` command

### ISSUE THREAD

**Issue by neoniobium** [jamke/qubes-completion#16]
We can significantly improve using salt in qubes when we provide further completion the `qubesctl` command.

Some basic completion for the first non-optional argument should at least be:
- [X] top.enable
- [X] top.disable
- [X] top.enabled 
- [X] state.highstate
- [X] state.apply

This will be easy to implement and could be easily expanded.

The really interesting part however would be to implement path completion the the salt commands that want one or more top files as an input. 

Unfortunately the target file's default directory is within `/srv/` which is only readable for the root user. Therefore I suppose we can only path complete after becoming root.

Furthermore after the top file[s] additional optional argument can be provided like `log-level=debug`

Therefor the full completion is something like

```
qubesctl [--qubes-options] salt-command path-to-top-file[s] [--salt-specific-arguments] 
```

References:
- https://www.qubes-os.org/doc/salt/
- https://docs.saltproject.io/en/latest/topics/using_salt.html
- In `dom0` run `salt-call --doc`

I volunteer to tackle this but I wanted open an issue first to discuss.

**Comment by jamke** [comment]
I am not using an expert in salt. Firstly, I see no much need for it in my cases, secondly, I prefer automation with scripts, it is more straight forward, easier for me to control and debug.
So, the only cases I was using salt is to create `sys-usb` and maybe a couple more, so, almost never.

When I was implementing `qubesctl` completion I was thinking about several things:
1. Documentation for `qubesctl` is quite bad, `man qubesctl` does not even mentions arguments that should be provided, not speaking of something like usage examples. So, I consider salt in Qubes OS to be rarely used niche thing. I understand the purpose, but I do not understand the way person would use it often, like several times a month.
2. Bad documentation of `qubesctl` forced me to read about salt on saltproject.io and I also was thinking to implement this `top.enable` and etc. But due to the lack of docs about Qubes OS I decided not to it, because I was afraid to provide something wrong. If you are certain about how `qubesctl` works with argument - feel free to provide PR about this arguments.
3. I also was considering providing the list of top files, it is not hard to implement, but root access to this folder ruined it. I do not think that we should provide this completion, because even if user uses `sudo` for command we still have not access to this list. And case when user works under `su` / `sudo -i`seems to be rare and should not be encouraged anyway. Maybe "common" or documentated top files can be provided blindly, but there is high changes these files will be renamed, removed and etc in future.

**Comment by jamke** [comment]
One more thing - I was considering to open the sources of `qubesctl` and get information from it, but thought that better to wait when `qubesctl` gets proper docs.

**Comment by neoniobium** [comment]
I use `salt` quite extensively nearly each day. I find I more keystroke efficient and easier to read on the fly then `bash` scripting. Furthermore I like to have documentation of all things I have done to my templates and a changelog. Therefor `salt+git` works well for me. Another plus is that migrating to a new template version or a new `qubes` version is done quickly.  

I agree that the documentation is horrific so I cannot guarantee to deliver the most complete solution possible. However I will provide completion based on my workflow. I think this suites basic needs well.

**Comment by jamke** [comment]
I also keep changes that I make to templates. I have to start with fedora-*-minimal, because I do not like GNOME apps, and prefer KDE app instead. Fedora is coming out quite often and quickly gets outdated (no LTS), so I have to repeat actions like 1-2 times a year to make a new pack of fedora-based templates. Unfortunately each time there are some differences in the list of actions - some packages are removed, some are not required anymore and etc.

So, I am rather interested in what you do and how (including salt action), maybe I should change my approach. Have you published your way of managing templates on forum, github or somewhere else?

**Comment by neoniobium** [comment]
> So, I am rather interested in what you do and how (including salt action), maybe I should change my approach.

I don't understand what the precise question is but my workflow is something like this.

1) Realizing at work that I need a `C`-library for some task.
2) Open `salt` vm add the line of code a `sls` file commit to `git`
3) Sync salt folder to `dom0`.
4) Execute salt task in `dom0`.

```
qubesctl --skip-dom0 --targets debain-11-minimal-pro state.apply <path>
```

Now I have the library in for all my programing templates --*work* and *personal*-- including disp-programing VM, a documentation for myself and a recipe for a fast reinstall if something breaks.

This is blow 5min of work.

Another example is my `vim` configuration: I would have noted that I want a new shortcut shortcut. So I add it and just copy the updated configuration file to the `salt` vm and distribute later to all vms so that `vim` is the same in all of them.

```
qubesctl --all state.apply <path>
```

I also like to update and clean all templates instead to just update them with qubes update. And somethings I want to switch from the `debian` `onion` repos to the normal reops before the update and then switch back.

```
qubesctl --templates state.apply <path>
```

Stuff like this is relatively clean code and done fast with `salt` if you used to it.

> Have you published your way of managing templates on forum, github or somewhere else?

Not I have not (yet). But this reminds me that I wanted to engage with the forum community for some time now but always forget it.

Consenting templates: All my `salt` stuff is heavily personalized, so publishing it is not a good idea. In principle however I could provide some basic salt recipes for some minimal templates on a spare weekend or so in the future.

Kind regrads,
Neoniobium.

**Comment by jamke** [comment]
I see, so you use it to sync configs between qubes and etc. I have a problem with configs - they include information related to the particular qube, like file paths, so in most cases if I want to change something in config of some app - it is not possible to change it for a bunch of qubes because it will affect qube-specific part of configs.

Forum is good, it has its obviously advantages over github for discussions.

**Comment by neoniobium** [comment]
Ok I have created a `qubes` forum account. Name is the same.

**Comment by jamke** [comment]
Should we consider it done?

**Comment by neoniobium** [comment]
I suppose yes.

If the permission for the `/srv/` folder won't change in future it's hard for me to think of anything reasonable to do here. I principle we could at `salt` path completion after the salt function, but I would only work for the root user.

**Comment by jamke** [comment]
OK, closing then. Thanks for contribution.
